name: Publish to PyPI
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the "main" branch
  push:
    branches: ["main"]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: ğŸ˜ Checkout
        uses: actions/checkout@main

      - name: ğŸ Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: ğŸ¦¤ Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: ğŸ¦‘ Fetch package version
        run: |
          echo "CURRENT_VERSION=v$(poetry version --short)" >> $GITHUB_ENV
          echo "Version = v$(poetry version --short)"

      - name: ğŸ— Build package
        if: |
          github.ref == 'refs/heads/main' && 
          github.event_name == 'push'
        run: poetry build

      - name: ğŸ“° Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: ğŸ·ï¸ Create tag
        if: |
          github.ref == 'refs/heads/main' && 
          github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.CURRENT_VERSION }}',
              sha: context.sha
            })